# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b954660007f85fd3895e818a27b02a2b9c78048477c6aa6d4f38545ff9df217c65e49eae9060d67924fed9c49945b505523bd8de9dd21455f0d3184364505445

test:
  secret_key_base: f1941f1e09dc0b6a219c22d2ddf522b2526d7c885049b80c097ca56ce068fafef1b954af59cda598c66f34c958d7cb3fc0d7b176ee70f6e14a50566c2259f989

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
